language: objective-c
xcode_project: BAPrayerTimes.xcodeproj
xcode_scheme: BAPrayerTimesTests
xcode_sdk: iphonesimulator
bundler_args: --without development documentation --deployment --jobs=3 --retry=3
after_success: bundle exec slather
cache: bundler
sudo: false
